# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/PHP.gitlab-ci.yml
stages:
  - build
  - test
  - deploy

default:
  cache:
    paths:
    - vendor/

build-php:
  stage: "build"
  only:
    - master
  artifacts:
    paths:
      - ./
  image: silarhi/php-apache:8.0-symfony    
  script:
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install --no-dev --optimize-autoloader
    - mkdir -p var && chmod -R 777 var

build-js:
  stage: "build"
  only:
    - master
  artifacts:
    paths:
      - ./
  image: node:latest
  script:
    - export NODE_OPTIONS=--openssl-legacy-provider
    - yarn install
    - yarn build
    - rm -r node_modules

build-docker:
  stage: "build"
  only:
    - master
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE_NAME: chibyjade/demo
    IMAGE_TAG: ${CI_PIPELINE_ID}
    APP_VERSION: ${IMAGE_TAG}
    GIT_COMMIT: ${CI_COMMIT_SHA}
  script:
    - echo ${DOCKER_PWD} | docker login -u ${DOCKER_LOGIN} --password-stdin
    - docker info
    - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} --build-arg APP_VERSION=${APP_VERSION} --build-arg GIT_COMMIT=${GIT_COMMIT} .
    - ./docker-tag.sh
    - docker push ${IMAGE_NAME}

# Bring in any services we need http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
# See http://docs.gitlab.com/ee/ci/services/README.html for examples.
# services:
#   - mysql:5.7

# Set any variables we need
variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  # MYSQL_DATABASE: mysql_database
  # MYSQL_ROOT_PASSWORD: mysql_strong_password
  APP_ENV: $APP_ENV

# Run our tests
# If Xdebug was installed you can generate a coverage report and see code coverage metrics.
test:
  stage: "test"
  only:
    - master
  image: silarhi/php-apache:8.0-symfony
  needs: ["build-php"]
  script:
    - export APP_ENV=test
    - php composer.phar install --optimize-autoloader
    - chmod 777 -R bin
    - bin/phpunit --coverage-text --colors=never

deploy:
  stage: "deploy"
  only:
    - master
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$DEPLOYER_PK" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >> ~/.ssh/config'
  script:
    - ssh ${DEPLOYER_USERNAME}@${PRODUCTION_SERVER_IP} "cd ${PRODUCTION_SERVER_PATH} && ./deploy.sh"