version: "3.9"

networks:
    web:
        external: true
    internal:
        external: false

services:
    demo:
        image: chibyjade/demo:latest
        networks:
        - internal
        - web
        restart: always
        environment:
            - APP_MAINTENANCE
            - APP_ENV
            - DATABASE_URL=sqlite:///%kernel.project_dir%/data/database.sqlite
            - APP_SECRET=2ca64f8d83b9e89f5f19d672841d6bb8
        volumes:
            - /app/var/logs
        labels:
        - "traefik.http.routers.demo.rule=Host(`demo.jadexau.fr`)"
        - "traefik.http.routers.demo.tls=true"
        - "traefik.http.routers.demo.tls.certresolver=lets-encrypt"
        - "traefik.port=80"
